
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectCDTT_63132701.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DonHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DonHang()
    {

        this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();

        this.ThanhToans = new HashSet<ThanhToan>();

        this.VanChuyens = new HashSet<VanChuyen>();

    }


    public int MaDH { get; set; }

    public Nullable<int> MaKH { get; set; }

    public decimal TongTien { get; set; }

    public string TrangThai { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public string MaVanDon { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

    public virtual KhachHang KhachHang { get; set; }

    public virtual HoaDon HoaDon { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ThanhToan> ThanhToans { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VanChuyen> VanChuyens { get; set; }

}

}
