
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectCDTT_63132701.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GiaVanChuyen
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GiaVanChuyen()
    {

        this.VanChuyens = new HashSet<VanChuyen>();

    }


    public int MaGiaVanChuyen { get; set; }

    public string DonViVanChuyen { get; set; }

    public decimal GiaVanChuyen1 { get; set; }

    public string DiaChiChiTiet { get; set; }

    public string PhuongXa { get; set; }

    public string QuanHuyen { get; set; }

    public string TinhThanh { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VanChuyen> VanChuyens { get; set; }

}

}
