//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCDTT_63132701.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gio_hang
    {
        public int id { get; set; }
        public int id_khach_hang { get; set; }
        public int id_san_pham { get; set; }
        public int so_luong { get; set; }
        public decimal gia { get; set; }
        public string trang_thai { get; set; }
    
        public virtual khach_hang khach_hang { get; set; }
        public virtual san_pham san_pham { get; set; }
    }
}
