//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCDTT_63132701.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gio_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gio_hang()
        {
            this.chi_tiet_gio_hang = new HashSet<chi_tiet_gio_hang>();
        }
    
        public int id { get; set; }
        public int id_khach_hang { get; set; }
        public System.DateTime ngay_dat_hang { get; set; }
        public string trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_gio_hang> chi_tiet_gio_hang { get; set; }
        public virtual khach_hang khach_hang { get; set; }
    }
}
