//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCDTT_63132701.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lich_su_truy_cap
    {
        public int id { get; set; }
        public Nullable<int> id_khach_hang { get; set; }
        public Nullable<int> id_san_pham { get; set; }
        public Nullable<System.DateTime> thoi_gian_truy_cap { get; set; }
    
        public virtual khach_hang khach_hang { get; set; }
        public virtual san_pham san_pham { get; set; }
    }
}
