//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCDTT_63132701.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanh_toan
    {
        public int id { get; set; }
        public Nullable<int> id_don_hang { get; set; }
        public string phuong_thuc { get; set; }
        public string trang_thai { get; set; }
        public string ma_giao_dich { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual don_hang don_hang { get; set; }
    }
}
